import { getOptionsForVote } from "@/utils/getRandomPokemon";
import type { NextPage } from "next";
import { useMemo, useState } from "react";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [ids, updateIds] = useState(() => getOptionsForVote());
  const [first, second] = ids;

  const firstPokemon = trpc.useQuery([
    "pokemon.get-pokemon-by-id",
    { id: first },
  ]);
  const secondPokemon = trpc.useQuery([
    "pokemon.get-pokemon-by-id",
    { id: second },
  ]);

  if (firstPokemon.isLoading || secondPokemon.isLoading) return null;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen flex flex-col justify-center items-center">
        <div className="text-2xl text-center">Which Pokemon is Rouder?</div>
        <div className="p-2" />
        <div className="border rounded p-8 flex justify-between max-w-2xl items-center">
          <div className="w-64 h-64 flex flex-col">
            <img
              src={firstPokemon.data?.sprites.front_default}
              className="w-full"
            />
            <div className="text-xl text-center capitalize mt-[-2rem]">
              {firstPokemon.data?.name}
            </div>
          </div>
          <div className="p-8"> vs.</div>
          <div className="w-64 h-64 flex flex-col">
            <img
              src={secondPokemon.data?.sprites.front_default}
              className="w-full"
            />
            <div className="text-xl text-center capitalize mt-[-2rem]">
              {secondPokemon.data?.name}
            </div>
          </div>
          <div className="p-2" />
        </div>
      </div>
    </>
  );
};

export default Home;
